version: '3.9'

networks:
  nestjs-clean:
    name: nestjs-clean
    driver: bridge

services:
  postgres:
    image: postgres:15.4-alpine3.18
    container_name: nestjs-clean-postgres
    ports:
      - 5433:5432
    env_file:
      - ./.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - nestjs-clean
